import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'etpn': 'Enter the Phone Number',
      'etvc': 'Enter the Verification Code',
      'wtw': 'Welcome the WhatsUp',
      'tvch': 'The verification code has been sent via sms to',
      'eypn': 'Enter your phone number',
      'verify': 'Verify',
      'settings': 'Settings',
      'new_group': 'New Group',
      'starred': 'Starred Messages',
      'new_broad': 'New Broadcast',
      'chats': 'CHATS',
      'status': 'STATUS',
      'calls': 'CALLS',
      'name': 'Name',
      'about': 'About',
      'phone': 'Phone',
      'cancel': 'Cancel',
      'save': 'Save',
      'eyn': 'Enter your name',
      'ways': 'Write about yourself',
      'wout': 'Watch out! This is visible.',
      'tap': 'Take a photo',
      'cog': 'Choose on gallery',
      'profile': 'Profile',
      'deleting': 'Deleting',
      'all_delete': 'All of the calls are deleted',
      'call_box': 'Calls box is empty',
      'lams': 'Look at my status',
      'ms': 'My Status',
      'ttas': 'Tap to add status update',
      'ws': 'Viewed Status',
      'nf': 'No Friends',
      'im': 'Image message',
      'sc': 'Select contact',
      'cs': 'contacts',
      'wc': 'View Contact',
      'mld': 'Media,links and docs',
      'cc': 'Clear chat',
      'search': 'Search',
      'mn': 'Mute notifications',
      'eb': 'No Message',
      'tam': 'Type a message'
    },
    'tr_TR': {
      'etpn': 'Telefon Numarasını Giriniz',
      'etvc': 'Doğrulama Kodunu Giriniz',
      'tvch': "Doğrulama kodu gönderildi",
      'wtw': "WhatsUp'a Hoşgeldiniz",
      'eypn': "Telefon numaranızı girin",
      'verify': "Doğrula",
      'settings': "Ayarlar",
      'new_group': "Yeni Grup",
      'starred': "Yıldızlı Mesajlar",
      'new_broad': "Yeni Toplu Mesaj",
      'chats': 'SOHBETLER',
      'status': 'DURUM',
      'calls': 'ARAMALAR',
      'name': 'İsim',
      'about': 'Hakkında',
      'phone': 'Telefon',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'eyn': 'İsminizi girin',
      'ways': 'Kendinden bahset',
      'wout': 'Herkes görebilir.Dikkat et!',
      'tap': 'Fotoğraf çek',
      'cog': 'Galeriden seç',
      'profile': 'Profil',
      'deleting': 'Silme İşlemi',
      'all_delete': 'Bütün aramalar silindi.',
      'call_box': 'Çağrı kutusu boş.',
      'lams': 'Durumuma bakın',
      'ms': 'Durumum',
      'ttas': 'Durumumu güncellemek için tıklayın.',
      'ws': 'Görülen durumlar',
      'nf': 'Arkadaş yok',
      'im': 'Medya mesajı',
      'sc': 'Kişi seç',
      'cs': 'kişi',
      'wc': 'Kişiyi görüntüle',
      'mld': 'Medya,bağlantılar ve belgeler',
      'cc': 'Sohbeti temizle',
      'search': 'Ara',
      'mn': 'Sessize al',
      'eb':'Mesaj Yok',
      'tam': 'Bir mesaj yazın'
    }
  };
}